import type { LegalDocument } from "./types";

const ro: LegalDocument = {
  title: "POLITICĂ DE CONFIDENȚIALITATE (GDPR)",
  lastUpdated: "August 2026",
  operator: "FIREFLY CONCEPT SRL",
  contact: "contact@fireflyapp.ro",
  blocks: [
  { type: "p", text: "Această Politică de Confidențialitate explică modul în care fireflyapp.ro colectează, utilizează și protejează datele cu caracter personal ale utilizatorilor simpli și ale partenerilor de afaceri (locații, organizatori de evenimente) care folosesc platforma noastră de promovare a petrecerilor." },
  { type: "h2", text: "1. Cine suntem noi?" },
  { type: "p", text: "Platforma fireflyapp.ro este operată de FIREFLY CONCEPT SRL. În calitate de operator de date cu caracter personal, ne asigurăm că procesăm datele tale în deplină conformitate cu Regulamentul General privind Protecția Datelor (GDPR - Regulamentul UE 2016/679)." },
  { type: "p", text: "Operatorul datelor tale este FIREFLY CONCEPT S.R.L., cu sediul social în Municipiul Piteşti, Jud. Argeş, Strada Constructorilor, Nr. 11, Bl. C, Scara B, Etaj PARTER, Ap. 3, înmatriculată sub nr. J2026039957007, CUI 54945577. Pentru orice întrebare legată de datele tale, ne poți contacta la adresa de e-mail: contact@fireflyapp.ro." },
  { type: "h2", text: "2. Ce date colectăm și de ce?" },
  { type: "h3", text: "A. Date oferite direct de tine:" },
  { type: "p", text: "Pentru contul de utilizator (cei care caută petreceri): Nume, prenume, adresă de e-mail, parolă (stocată securizat prin criptare/hashing)." },
  { type: "p", text: "Pentru contul de business (locații / organizatori de evenimente): Numele companiei/locației, datele de identificare ale reprezentantului — necesară pentru administrarea contului și relația contractuală cu business-ul, e-mail de contact, număr de telefon, CUI, sediu social și materialele încărcate pentru promovarea evenimentelor (titluri, descrieri, poze, locație)." },
  { type: "p", text: "Date privind tranzacțiile: Pentru plățile efectuate prin platformă putem colecta informații precum suma, moneda, data tranzacției, identificatorul tranzacției, statusul plății și datele de facturare. Plățile cu cardul sunt procesate prin furnizorul nostru de plăți, Stripe, iar Firefly nu stochează numărul complet al cardului sau codul CVC." },
  { type: "p", text: "Pentru newsletter și marketing (opțional): Adresa de e-mail — colectată doar dacă bifezi explicit că dorești să primești noutăți și recomandări despre petreceri." },
  { type: "p", text: "Pentru formularul de contact: Nume, e-mail și mesajul tău — folosite exclusiv pentru a-ți răspunde la solicitare." },
  { type: "h3", text: "B. Date colectate automat (tehnice):" },
  { type: "p", text: "Jurnale de securitate (server logs): adresa IP, tipul de browser utilizat, paginile accesate și data/ora accesului — păstrate temporar pentru protecția cibernetică a platformei." },
  { type: "h2", text: "3. De ce și în ce temei îți procesăm datele?" },
  { type: "p", text: "Procesăm datele tale cu caracter personal în următoarele scopuri:" },
  { type: "p", text: "Furnizarea serviciilor: Crearea și administrarea contului tău, logarea securizată și afișarea conținutului relevant (Temei legal: Executarea contractului / Termenii și Condițiile - Art. 6(1)(b) GDPR)." },
  { type: "p", text: "Procesarea și gestionarea plăților: Pentru procesarea plăților pentru abonamente, promovare și alte servicii oferite prin platformă, precum și pentru prevenirea și detectarea fraudelor și gestionarea eventualelor dispute privind tranzacțiile (Temei legal: Executarea contractului – Art. 6(1)(b) GDPR și, după caz, interesul legitim – Art. 6(1)(f) GDPR)." },
  { type: "p", text: "Comunicare funcțională: Trimiterea de e-mailuri tranzacționale (confirmarea contului, resetare de parolă, notificări legate de petreceri) (Temei legal: Executarea contractului)." },
  { type: "p", text: "Securitate și prevenirea fraudelor: Monitorizarea traficului pentru a preveni atacurile informatice sau conturile false (Temei legal: Interesul nostru legitim - Art. 6(1)(f) GDPR)." },
  { type: "p", text: "Newsletter / Comunicări de marketing: Trimiterea de recomandări despre evenimente din București (Temei legal: Consimțământul tău explicit - exprimat prin bifă separată)." },
  { type: "h2", text: "4. Cât timp păstrăm datele?" },
  { type: "p", text: "Păstrăm datele cu caracter personal doar atât timp cât este necesar pentru îndeplinirea scopurilor menționate:" },
  { type: "p", text: "Datele asociate conturilor (User și Business) sunt păstrate pe întreaga perioadă în care contul este activ. Dacă decizi să ștergi contul, datele tale vor fi șterse sau anonimizate, cu excepția celor pe care suntem obligați prin lege să le păstrăm." },
  { type: "p", text: "Datele privind tranzacțiile și documentele financiar-contabile sunt păstrate pe perioada prevăzută de legislația fiscală și contabilă aplicabilă, chiar și după ștergerea contului, atunci când există o obligație legală de păstrare." },
  { type: "p", text: "Datele pentru newsletter sunt păstrate până când îți retragi consimțământul sau te dezabonezi de la comunicările de marketing." },
  { type: "p", text: "Jurnalele tehnice (server logs): Se șterg automat după 30 de zile." },
  { type: "h2", text: "5. Cu cine partajăm datele?" },
  { type: "p", text: "Nu vindem și nu închiriem datele tale către terți. Datele tale pot fi accesate doar de furnizori de servicii strict necesari pentru funcționarea site-ului:" },
  { type: "ul", items: [
    "Furnizorul de găzduire web (hosting), stocare media și servicii IT.",
    "Furnizori de servicii de e-mail marketing",
    "Autorități ale statului (dacă există o obligație legală).",
  ] },
  { type: "rich", parts: [
    { text: "Furnizori de servicii de plată: Pentru procesarea plăților online, utilizăm Stripe. Atunci când efectuezi o plată prin platformă, anumite date necesare procesării tranzacției (precum numele, adresa de e-mail, datele tranzacției și informațiile necesare pentru plată) pot fi transmise către Stripe. Datele cardului sunt introduse și procesate prin infrastructura Stripe și nu sunt stocate de Firefly în format complet (" },
    { text: "Politica de confidențialitate Stripe", href: "https://stripe.com/privacy", external: true },
    { text: ")." },
  ] },
  { type: "callout", text: "Notă! Transferuri internaționale de date: Unii dintre furnizorii noștri de servicii pot prelucra date cu caracter personal în afara Spațiului Economic European. În astfel de situații, ne asigurăm că transferurile sunt realizate în conformitate cu GDPR și că sunt utilizate mecanisme legale adecvate, precum o Decizie de adecvare a Comisiei Europene, Standard Contractual Clauses (SCCs) sau alte mecanisme recunoscute de legislația aplicabilă." },
  { type: "h2", text: "6. Drepturile tale (GDPR)" },
  { type: "p", text: "În calitate de utilizator, ai următoarele drepturi garantate:" },
  { type: "ul", items: [
    "Dreptul de acces: Poți cere o copie a datelor pe care le avem despre tine.",
    "Dreptul la rectificare: Poți cere corectarea datelor greșite.",
    "Dreptul la ștergere („dreptul de a fi uitat”): Poți cere ștergerea contului și a datelor tale.",
    "Dreptul de a retrage consimțământul: Te poți dezabona oricând de la comunicările de marketing.",
    "Dreptul la restricționarea prelucrării;",
    "Dreptul la portabilitatea datelor, atunci când sunt îndeplinite condițiile legale;",
    "Dreptul de opoziție, în special față de prelucrările bazate pe interes legitim și față de marketing direct;",
    "Dreptul de a nu face obiectul unei decizii bazate exclusiv pe prelucrare automată, inclusiv profilare, în condițiile prevăzute de GDPR.",
  ] },
  { type: "p", text: "Vom răspunde solicitării tale fără întârzieri nejustificate și, în principiu, în termen de o lună de la primirea solicitării. În cazurile permise de GDPR, acest termen poate fi prelungit cu cel mult două luni, cu informarea ta." },
  { type: "rich", parts: [
    { text: "De asemenea, ai dreptul de a depune o plângere la autoritatea de supraveghere din România: ANSPDCP (" },
    { text: "www.dataprotection.ro", href: "https://www.dataprotection.ro", external: true },
    { text: ")." },
  ] },
  { type: "h2", text: "7. Securitatea datelor tale" },
  { type: "p", text: "Aplicăm măsuri tehnice moderne pentru a-ți proteja informațiile: conexiuni criptate HTTPS/TLS, stocarea securizată a parolelor (bcrypt hashing), protecție împotriva atacurilor de tip brute-force și limite de conectare." },
  { type: "h2", text: "8. Cookie-uri" },
  { type: "rich", parts: [
    { text: "Folosim exclusiv cookie-uri tehnice și strict necesare pentru menținerea sesiunii tale de autentificare și securitate. Pentru detalii complete, consultă " },
    { text: "Politica de Cookie-uri", href: "/cookies" },
    { text: "." },
  ] },
  { type: "h2", text: "9. Protecția minorilor" },
  { type: "p", text: "Platforma Firefly este destinată persoanelor cu vârsta de 18 ani sau peste. Nu permitem crearea de conturi de către persoane sub 18 ani și nu colectăm cu bună știință date cu caracter personal de la minori. Dacă aflăm că am colectat astfel de date, vom lua măsurile necesare pentru ștergerea acestora." },
  { type: "h2", text: "10. Modificări ale politicii" },
  { type: "p", text: "Ne rezervăm dreptul de a actualiza prezenta politică. În cazul unor modificări majore, te vom notifica prin e-mail sau printr-o alertă pe site înainte ca acestea să intre în vigoare." },
  ],
};

const en: LegalDocument = {
  title: "PRIVACY POLICY (GDPR)",
  lastUpdated: "August 2026",
  operator: "FIREFLY CONCEPT SRL | Romania",
  contact: "contact@fireflyapp.ro",
  blocks: [
  { type: "p", text: "This Privacy Policy explains how fireflyapp.ro collects, uses, and protects the personal data of regular users and business partners (venues, event organizers) who use our party promotion platform." },
  { type: "h2", text: "1. Who We Are" },
  { type: "p", text: "The fireflyapp.ro platform is operated by FIREFLY CONCEPT SRL. As a data controller, we ensure that your data is processed in full compliance with the General Data Protection Regulation (GDPR - Regulation EU 2016/679)." },
  { type: "p", text: "The controller of your data is FIREFLY CONCEPT S.R.L., with its registered office in Pitești Municipality, Argeș County, 11 Constructorilor Street, Block C, Entrance B, Ground Floor, Ap. 3, registered under no. J2026039957007, Tax ID (CUI) 54945577. For any questions regarding your data, you can contact us at: contact@fireflyapp.ro." },
  { type: "h2", text: "2. What Data We Collect and Why" },
  { type: "h3", text: "A. Data provided directly by you:" },
  { type: "p", text: "For user accounts (people looking for parties): First name, last name, email address, and password (stored securely using encryption/hashing)." },
  { type: "p", text: "For business accounts (venues / event organizers): Company/venue name, identification details of the representative – necessary for account administration and the contractual relationship with the business, contact email address, phone number, CUI, registered office, and materials uploaded for event promotion (titles, descriptions, photos, location)." },
  { type: "p", text: "Transaction data: For payments made through the platform, we may collect information such as the amount, currency, transaction date, transaction identifier, payment status, and billing information. Card payments are processed through our payment service provider, Stripe, and Firefly does not store the full card number or CVC." },
  { type: "p", text: "For newsletters and marketing (optional): Email address – collected only if you explicitly check the box indicating that you wish to receive news and recommendations about parties." },
  { type: "p", text: "For the contact form: Name, email address, and your message – used exclusively to respond to your inquiry." },
  { type: "h3", text: "B. Data collected automatically (technical):" },
  { type: "p", text: "Security logs (server logs): IP address, browser type, pages accessed, and date/time of access – temporarily stored for the cybersecurity protection of the platform." },
  { type: "h2", text: "3. Why and On What Grounds We Process Your Data" },
  { type: "p", text: "We process your personal data for the following purposes:" },
  { type: "p", text: "Providing our services: Creating and managing your account, secure login, and displaying relevant content (Legal basis: Performance of a contract / Terms and Conditions – Article 6(1)(b) GDPR)." },
  { type: "p", text: "Processing and managing payments: Processing payments for subscriptions, promotion, and other services offered through the platform, as well as preventing and detecting fraud and managing potential transaction disputes (Legal basis: Performance of a contract – Article 6(1)(b) GDPR and, where applicable, legitimate interests – Article 6(1)(f) GDPR)." },
  { type: "p", text: "Functional communications: Sending transactional emails (account confirmation, password reset, party-related notifications) (Legal basis: Performance of a contract)." },
  { type: "p", text: "Security and fraud prevention: Monitoring traffic to prevent cyberattacks and fake accounts (Legal basis: Legitimate interests – Article 6(1)(f) GDPR)." },
  { type: "p", text: "Newsletter / Marketing communications: Sending recommendations about events in Bucharest (Legal basis: Your explicit consent – provided through a separate checkbox)." },
  { type: "h2", text: "4. How Long We Retain Data" },
  { type: "p", text: "We retain personal data only for as long as necessary to fulfill the stated purposes:" },
  { type: "p", text: "Data associated with User and Business accounts is retained for as long as the account remains active. If you decide to delete your account, your data will be deleted or anonymized, except for data that we are legally required to retain." },
  { type: "p", text: "Transaction data and financial/accounting documents are retained for the period required by applicable tax and accounting legislation, even after account deletion, where there is a legal obligation to retain them." },
  { type: "p", text: "Newsletter data is retained until you withdraw your consent or unsubscribe from marketing communications." },
  { type: "p", text: "Technical logs (server logs): Automatically deleted after 30 days." },
  { type: "h2", text: "5. Who We Share Data With" },
  { type: "p", text: "We do not sell or rent your personal data to third parties. Your data is accessed only by service providers strictly necessary for the platform's operation:" },
  { type: "ul", items: [
    "Web hosting providers, media storage providers, and IT service providers.",
    "Email marketing service providers.",
  ] },
  { type: "rich", parts: [
    { text: "Payment service providers: We use Stripe to process online payments. When you make a payment through the platform, certain data necessary to process the transaction (such as your name, email address, transaction data, and information required for payment) may be transmitted to Stripe. Card details are entered and processed through Stripe's infrastructure and are not stored by Firefly in full. " },
    { text: "See Stripe's Privacy Policy.", href: "https://stripe.com/privacy", external: true },
  ] },
  { type: "ul", items: [
    "Government authorities, where required by law.",
  ] },
  { type: "p", text: "International data transfers: Some of our service providers may process personal data outside the European Economic Area (EEA). In such cases, we ensure that transfers are carried out in accordance with the GDPR and that appropriate legal mechanisms are used, such as an adequacy decision by the European Commission, Standard Contractual Clauses (SCCs), or other mechanisms recognized under applicable law." },
  { type: "h2", text: "6. Your Rights (GDPR)" },
  { type: "p", text: "As a user, you have the following guaranteed rights:" },
  { type: "ul", items: [
    "Right of access: You may request a copy of the personal data we hold about you.",
    "Right to rectification: You may request correction of inaccurate personal data.",
    "Right to erasure (“right to be forgotten”): You may request deletion of your account and personal data.",
    "Right to withdraw consent: You may unsubscribe from marketing communications at any time.",
    "Right to restriction of processing.",
    "Right to data portability, where the applicable legal conditions are met.",
    "Right to object, particularly to processing based on legitimate interests and to direct marketing.",
    "Right not to be subject to a decision based solely on automated processing, including profiling, where provided for under the GDPR.",
  ] },
  { type: "p", text: "We will respond to your request without undue delay and, in principle, within one month of receiving it. In cases permitted by the GDPR, this period may be extended by up to two additional months, and you will be informed accordingly." },
  { type: "rich", parts: [
    { text: "You also have the right to lodge a complaint with the national supervisory authority in Romania: ANSPDCP " },
    { text: "ANSPDCP (www.dataprotection.ro)", href: "https://www.dataprotection.ro", external: true },
    { text: "." },
  ] },
  { type: "h2", text: "7. Data Security" },
  { type: "p", text: "We apply modern technical measures to safeguard your information: encrypted HTTPS/TLS connections, secure password storage (bcrypt hashing), brute-force protection, and login attempt limits." },
  { type: "h2", text: "8. Cookies" },
  { type: "rich", parts: [
    { text: "We use strictly necessary technical cookies to maintain your authentication session and platform security. For full details, please consult our " },
    { text: "Cookie Policy", href: "/cookies" },
    { text: "." },
  ] },
  { type: "h2", text: "9. Protection of Minors" },
  { type: "p", text: "The Firefly platform is intended for persons aged 18 and over. We do not allow persons under the age of 18 to create accounts and do not knowingly collect personal data from minors. If we become aware that we have collected such data, we will take the necessary steps to delete it." },
  { type: "h2", text: "10. Policy Changes" },
  { type: "p", text: "We reserve the right to update this policy. In the event of material changes, we will notify you by email or via an alert on the website before the changes take effect." },
  ],
};

export const privacyContent: Record<"en" | "ro", LegalDocument> = { en, ro };
