import type { LegalDocument } from "./types";

const ro: LegalDocument = {
  title: "TERMENI ȘI CONDIȚII DE UTILIZARE",
  lastUpdated: "August 2026",
  operator: "FIREFLY CONCEPT SRL",
  contact: "contact@fireflyapp.ro",
  blocks: [
  { type: "h2", text: "1. Acceptarea termenilor" },
  { type: "p", text: "Bun venit pe fireflyapp.ro! Proprietarul și administratorul acestui site este FIREFLY CONCEPT S.R.L., înmatriculată sub nr. J2026039957007, CUI 54945577." },
  { type: "p", text: "Prin accesarea platformei fireflyapp.ro, înregistrarea unui cont sau utilizarea serviciilor noastre, ești de acord să respecți prezenții Termeni și Condiții. Dacă nu ești de acord cu aceste reguli, te rugăm să nu utilizezi platforma." },
  { type: "h2", text: "2. Despre platformă" },
  { type: "p", text: "Firefly este o platformă online de promovare și agregare a evenimentelor și petrecerilor din București." },
  { type: "p", text: "Furnizăm:" },
  { type: "ul", items: [
    "Instrumente de căutare, salvare și recomandare de evenimente pentru utilizatorii simpli.",
    "Instrumente de publicare și gestionare a paginilor de eveniment pentru conturile de tip Business (locații, organizatori).",
    "Funcționalități interactive (cum ar fi hărți ale locațiilor).",
  ] },
  { type: "callout", text: "IMPORTANT: Platforma noastră acționează exclusiv ca un furnizor de servicii informaționale și de promovare. Noi NU organizăm evenimentele publicate, NU controlăm desfășurarea petrecerilor și NU vindem direct bilete (atunci când sunt disponibile linkuri către platforme externe de ticketing, achiziția biletelor se realizează direct prin furnizorul respectiv)." },
  { type: "h2", text: "3. Conturile de utilizator (cei care caută petreceri)" },
  { type: "p", text: "Crearea contului: Trebuie să furnizezi date reale și să îți validezi adresa de e-mail pentru acces complet." },
  { type: "p", text: "Vârsta minimă: Crearea unui cont pe platformă este permisă exclusiv persoanelor care au împlinit vârsta de 18 ani." },
  { type: "p", text: "Securitatea contului: Ești pe deplin responsabil de păstrarea confidențialității parolei tale." },
  { type: "p", text: "Restricții: Este interzisă crearea de conturi multiple de către aceeași persoană pentru a eluda blocările sau restricțiile aplicate anterior de administratori." },
  { type: "h2", text: "4. Conturile de Business (organizatori petreceri și locații)" },
  { type: "p", text: "Organizatorii și localurile care își creează cont business și publică conținut pe platformă se obligă:" },
  { type: "ul", items: [
    "Să publice doar evenimente pe care au dreptul legal de a le organiza sau promova.",
    "Să ofere informații exacte și actualizate (dată, oră, locație, prețuri bilete, linie de artiști).",
    "Să actualizeze sau să anuleze prompt pagina evenimentului de pe site în cazul în care intervin modificări.",
    "Să nu publice evenimente cu caracter ilegal, dezinformator, cu tentă discriminatorie sau obscenă.",
    "Să garanteze că dețin toate drepturile de utilizare pentru imaginile, textul, logo-urile sau materialele video încărcate pe platformă. fireflyapp.ro nu poate fi tras la răspundere pentru încălcarea drepturilor de autor de către parteneri.",
  ] },
  { type: "p", text: "Ne rezervăm dreptul de a modera, refuza, elimina sau restricționa accesul la orice eveniment care încalcă acești Termeni, legislația aplicabilă sau regulile platformei. În funcție de circumstanțe, aceste măsuri pot fi luate fără notificare prealabilă, în măsura permisă de lege." },
  { type: "h2", text: "5. Servicii plătite și plăți" },
  { type: "p", text: "Firefly oferă conturilor Business servicii opționale de promovare și vizibilitate. Prețurile aplicabile sunt afișate pe platformă înainte de efectuarea plății. Firefly nu este plătitoare de TVA." },
  { type: "p", text: "Serviciile disponibile includ:" },
  { type: "ul", items: [
    "Promoted Event – 150 lei / eveniment Promovarea unui eveniment în feed-ul și pe harta Firefly.",
    "“What Did You Miss?” Post – 100 lei / postare Publicarea unei postări promoționale în secțiunea „What Did You Miss?”, sub rezerva aprobării Firefly.",
    "Newsletter – 150 lei / includere Includerea unui business, eveniment sau material promoțional într-o ediție a newsletterului Firefly, sub rezerva aprobării.",
    "Social Media Content – 150 lei / postare Includerea business-ului sau a materialului promoțional într-o postare pe canalele oficiale de social media Firefly, sub rezerva aprobării.",
    "Premium Subscription – 500 lei / lună, care include:",
    "4 Promoted Events;",
    "4 “What Did You Miss?” Posts;",
    "1 Newsletter inclusion;",
    "2 Social Media Posts.",
  ] },
  { type: "p", text: "Plata se poate efectua prin metodele disponibile pe platformă, inclusiv prin Stripe. Datele complete ale cardului sunt procesate de furnizorul de plăți și nu sunt stocate de Firefly." },
  { type: "p", text: "Serviciile individuale sunt furnizate după confirmarea cu succes a plății. Abonamentul Premium este, implicit, o achiziție pentru o singură lună: după confirmarea plății, beneficiile sunt disponibile până la finalul perioadei plătite, fără reînnoire automată. Reînnoirea lunară automată este opțională și se activează doar dacă business-ul bifează explicit această opțiune înainte de plată." },
  { type: "p", text: "Dacă auto-reînnoirea este activată, Stripe debitează metoda de plată salvată în fiecare lună. Anularea reînnoirii automate oprește următoarea plată și nu afectează perioada deja plătită, cu excepția cazului în care legislația aplicabilă prevede altfel. Poți gestiona sau anula abonamentul din Business Dashboard sau din pagina Stripe de facturare." },
  { type: "p", text: "Condițiile de anulare și rambursare sunt cele afișate la momentul achiziției și cele prevăzute de legislația aplicabilă. Serviciile de promovare deja furnizate sau începute pot să nu fie rambursabile, în măsura permisă de lege." },
  { type: "p", text: "În cazul unei plăți eșuate la reînnoire, Stripe poate reîncerca automat încasarea. Beneficiile Premium rămân disponibile în perioada de retry. Dacă plata nu reușește după încercările configurate, Firefly suspendă beneficiile Premium până la actualizarea metodei de plată sau până la o plată reușită. Abonamentul poate fi ulterior marcat ca neplătit sau anulat." },
  { type: "p", text: "Beneficiile incluse în abonamentul Premium sunt disponibile pentru fiecare perioadă lunară de facturare. Beneficiile Premium neutilizate într-o perioadă de facturare nu se reportează automat în perioada următoare." },
  { type: "h2", text: "6. Link-uri către alte site-uri" },
  { type: "p", text: "Site-ul poate conține link-uri către platforme de ticketing (ex: IaBilet, Entertix) sau pagini de social media ale cluburilor. Nu avem niciun control asupra acestor site-uri terțe și nu ne asumăm responsabilitatea pentru politicile lor, tranzacțiile financiare sau conținutul lor." },
  { type: "h2", text: "7. Evenimente publicate de Firefly" },
  { type: "p", text: "Firefly poate publica și administra informații despre evenimente disponibile public, provenite inclusiv de pe site-urile oficiale ale organizatorilor și locațiilor, paginile publice de social media și platformele publice de ticketing, exclusiv în scop informativ." },
  { type: "p", text: "Aceste informații pot fi introduse manual de Firefly sau furnizate direct de organizatori și pot include, printre altele, numele evenimentului, data, ora, locația, prețul biletelor, lineup-ul și linkurile către platformele de ticketing." },
  { type: "p", text: "Firefly poate reformula sau adapta informațiile despre evenimente în scopul prezentării acestora pe platformă și depune eforturi rezonabile pentru menținerea informațiilor actualizate. Firefly nu este organizatorul acestor evenimente și nu garantează că informațiile nu pot suferi modificări de ultim moment din partea organizatorilor. Utilizatorii sunt sfătuiți să verifice detaliile oficiale accesând linkul către sursa originală/bilet furnizat pe pagina fiecărui eveniment." },
  { type: "p", text: "Publicarea unui eveniment pe Firefly nu implică în mod automat existența unui parteneriat sau a unei colaborări comerciale între Firefly și organizatorul sau locația respectivă." },
  { type: "p", text: "Organizatorii sau locațiile care doresc modificarea ori eliminarea unui eveniment sau a unor informații publicate despre acesta ne pot contacta la contact@fireflyapp.ro." },
  { type: "h2", text: "8. Comportamente interzise" },
  { type: "p", text: "Utilizatorilor și partenerilor le este strict interzis:" },
  { type: "ul", items: [
    "Să folosească platforma în scopuri ilegale sau pentru distribuirea de conținut dăunător.",
    "Să încerce compromiterea securității site-ului (hacking, scraping automatizat, crawling neautorizat, atacuri de tip denial-of-service).",
    "Să preia identitatea unei alte persoane fizice sau juridice.",
    "Să încarce materiale care încalcă drepturile de autor, mărcile înregistrate sau drepturile la imagine ale unor terți.",
  ] },
  { type: "h2", text: "9. Proprietate intelectuală și conținut" },
  { type: "p", text: "Conținutul tău: Îți păstrezi drepturile de autor asupra imaginilor, textelor și logo-urilor pe care le încarci pe platformă. Prin publicarea lor pe fireflyapp.ro, ne acorzi o licență neexclusivă, gratuită și valabilă global de a afișa și promova acel conținut în cadrul aplicației și pe canalele noastre oficiale de social media, pe durata în care conținutul este disponibil pe platformă și pentru o perioadă rezonabilă ulterior, exclusiv în scopul promovării Firefly și a evenimentelor publicate." },
  { type: "callout", text: "Notă! Ne rezervăm dreptul de a elimina, modifica sau restricționa accesul la orice conținut care încalcă acești Termeni, legislația aplicabilă sau regulile platformei" },
  { type: "p", text: "Conținutul platformei: Designul, codul sursă, mărci precum Firefly și textul original al platformei aparțin exclusiv FIREFLY CONCEPT SRL." },
  { type: "h2", text: "10. Limitarea răspunderii (Exonerare)" },
  { type: "p", text: "Platforma este pusă la dispoziție „ca atare”. În cea mai mare măsură permisă de lege, FIREFLY CONCEPT SRL nu este răspunzătoare pentru:" },
  { type: "ul", items: [
    "Anularea, amânarea sau modificarea petrecerilor ori a condițiilor de acces stabilite de organizatori.",
  ] },
  { type: "p", text: "Incidentele, prejudiciile sau pagubele materiale/fizice suferite de utilizatori în cadrul locațiilor sau evenimentelor promovate." },
  { type: "p", text: "Eventualele întreruperi temporare ale serviciului cauzate de erori tehnice, lucrări de mentenanță sau atacuri cibernetice." },
  { type: "callout", text: "Notă! Informațiile privind evenimentele sunt furnizate de organizatori sau locații. Firefly depune eforturi rezonabile pentru a menține informațiile actualizate, însă nu garantează că toate informațiile furnizate de terți sunt complete, exacte sau actualizate în orice moment." },
  { type: "h2", text: "11. Suspendarea contului" },
  { type: "p", text: "Ne rezervăm dreptul de a suspenda sau închide temporar ori permanent un cont care încalcă acești Termeni, legislația aplicabilă sau regulile platformei, inclusiv în situații de fraudă, abuz, încălcări repetate sau amenințări la adresa securității platformei." },
  { type: "h2", text: "12. Legea aplicabilă și jurisdicția" },
  { type: "p", text: "Acești Termeni sunt guvernați de legislația română. În cazul utilizatorilor care beneficiază de protecția conferită de legislația privind protecția consumatorilor, se aplică și dispozițiile imperative relevante, inclusiv cele privind competența instanțelor. Pentru celelalte situații, litigiile vor fi soluționate de instanțele competente potrivit legislației aplicabile." },
  { type: "h2", text: "13. Disponibilitatea platformei" },
  { type: "p", text: "Firefly depune eforturi rezonabile pentru a menține platforma disponibilă și funcțională, însă nu garantează funcționarea neîntreruptă sau lipsa erorilor. Platforma poate fi temporar indisponibilă pentru mentenanță, actualizări, probleme tehnice sau cauze aflate în afara controlului Firefly." },
  { type: "h2", text: "14. Modificarea termenilor" },
  { type: "p", text: "Ne rezervăm dreptul de a modifica acești termeni în funcție de schimbările legislative sau de funcționalitățile site-ului. Modificările devin aplicabile din momentul publicării pe site. Continuarea utilizării site-ului după intrarea în vigoare a modificărilor reprezintă acceptarea acestora." },
  ],
};

const en: LegalDocument = {
  title: "TERMS AND CONDITIONS OF USE",
  lastUpdated: "August 2026",
  operator: "FIREFLY CONCEPT SRL",
  contact: "contact@fireflyapp.ro",
  blocks: [
  { type: "h2", text: "1. Acceptance of Terms" },
  { type: "p", text: "Welcome to fireflyapp.ro! The owner and administrator of this website is FIREFLY CONCEPT S.R.L., registered under no. J2026039957007, VAT ID (CUI) 54945577." },
  { type: "p", text: "By accessing the fireflyapp.ro platform, registering an account, or using our services, you agree to comply with these Terms and Conditions. If you do not agree with these rules, please do not use the platform." },
  { type: "h2", text: "2. About the Platform" },
  { type: "p", text: "Firefly is an online platform for promoting and aggregating events and parties in Bucharest." },
  { type: "p", text: "We provide:" },
  { type: "ul", items: [
    "Event search, bookmarking, and recommendation tools for regular users.",
    "Event publishing and management tools for Business accounts (venues, event organizers).",
    "Interactive features (such as venue maps).",
  ] },
  { type: "callout", text: "IMPORTANT: Our platform acts exclusively as an information and promotional services provider. We DO NOT organize the events published on the platform, DO NOT control the way parties or events are conducted, and DO NOT sell tickets directly (when links to external ticketing platforms are available, tickets are purchased directly through the respective provider)." },
  { type: "h2", text: "3. User Accounts (Party-goers)" },
  { type: "p", text: "Account Creation: You must provide accurate information and verify your email address for full access." },
  { type: "p", text: "Minimum Age: Creating an account on the platform is permitted for individuals aged 18 and older (or 16 with guardian consent, where applicable). Physical access to promoted events follows the specific rules of each venue (e.g., 18+ restrictions)." },
  { type: "p", text: "Account Security: You are fully responsible for maintaining the confidentiality of your password." },
  { type: "p", text: "Restrictions: Creating multiple accounts by the same individual to bypass previously issued bans or restrictions by administrators is strictly prohibited." },
  { type: "h2", text: "4. Business Accounts (Party Organizers and Venues)" },
  { type: "p", text: "Organizers and venues creating a business account and publishing content on the platform agree to:" },
  { type: "ul", items: [
    "Publish only events that they are legally entitled to organize or promote.",
    "Provide accurate and up-to-date information (date, time, location, ticket prices, artist lineup).",
    "Promptly update or cancel the event page on the platform if any changes occur.",
    "Not publish events that are illegal, misleading, discriminatory, or obscene.",
    "Guarantee that they hold all necessary rights to use the images, text, logos, or video materials uploaded to the platform. fireflyapp.ro shall not be held liable for copyright infringements committed by partners.",
  ] },
  { type: "p", text: "We reserve the right to moderate, reject, remove, or restrict access to any event that violates these Terms, applicable law, or the platform's rules. Depending on the circumstances, such measures may be taken without prior notice, to the extent permitted by law." },
  { type: "h2", text: "5. Paid Services and Payments" },
  { type: "p", text: "Firefly offers Business accounts optional promotional and visibility services. Applicable prices are displayed on the platform before payment is made. Firefly is not VAT registered." },
  { type: "p", text: "Available services include:" },
  { type: "ul", items: [
    "Promoted Event – RON 150 / event Promotion of an event in the Firefly feed and on the Firefly map.",
    "“What Did You Miss?” Post – RON 100 / post Publication of a promotional post in the “What Did You Miss?” section, subject to Firefly approval.",
    "Newsletter – RON 150 / inclusion Inclusion of a business, event, or promotional material in one edition of the Firefly newsletter, subject to approval.",
    "Social Media Content – RON 150 / post Inclusion of the business or promotional material in a post on Firefly's official social media channels, subject to approval.",
    "Premium Subscription – RON 500 / month, including:",
    "4 Promoted Events;",
    "4 “What Did You Miss?” Posts;",
    "1 Newsletter inclusion;",
    "2 Social Media Posts.",
  ] },
  { type: "p", text: "Payment may be made through the payment methods available on the platform, including Stripe. Full card details are processed by the payment provider and are not stored by Firefly." },
  { type: "p", text: "Individual services are provided after successful payment confirmation. The Premium Subscription is, by default, a one-month purchase: after payment is confirmed, benefits are available until the end of the paid period, without automatic renewal. Monthly auto-renewal is optional and is enabled only if the business explicitly checks this option before payment." },
  { type: "p", text: "If auto-renewal is enabled, Stripe charges the saved payment method each month. Cancelling automatic renewal stops the next charge and does not affect the period already paid for, except where otherwise required by applicable law. You can manage or cancel the subscription from the Business Dashboard or the Stripe billing portal." },
  { type: "p", text: "Cancellation and refund conditions are those displayed at the time of purchase and those provided by applicable law. Promotional services that have already been provided or have already commenced may be non-refundable, to the extent permitted by law." },
  { type: "p", text: "If a renewal payment fails, Stripe may retry collection automatically. Premium benefits remain available during the retry window. If payment still cannot be completed after the configured retries, Firefly suspends Premium benefits until the payment method is updated or payment succeeds. The subscription may then be marked unpaid or cancelled." },
  { type: "p", text: "The benefits included in the Premium Subscription are available for each monthly billing period. Unused Premium benefits from one billing period do not automatically carry over to the following period." },
  { type: "h2", text: "6. Links to Other Websites" },
  { type: "p", text: "The website may contain links to third-party ticketing platforms (e.g., IaBilet, Entertix) or social media pages of clubs. We have no control over these third-party websites and assume no responsibility for their policies, financial transactions, or content." },
  { type: "h2", text: "7. Events Published by Firefly" },
  { type: "p", text: "Firefly may publish and manage information about publicly available events, sourced from official organizer and venue websites, public social media pages, and public ticketing platforms, strictly for informational purposes." },
  { type: "p", text: "This information may be entered manually by Firefly or provided directly by organizers and may include, among other details, the event name, date, time, location, ticket prices, lineup, and links to ticketing platforms." },
  { type: "p", text: "Firefly may rephrase or adapt event information for presentation purposes on the platform and makes reasonable efforts to keep information up to date. Firefly is not the organizer of these events and does not guarantee that information will not undergo last-minute changes by the organizers. Users are advised to verify official details by accessing the link to the original source/ticket provided on each event page." },
  { type: "p", text: "The publication of an event on Firefly does not automatically imply the existence of a partnership or commercial collaboration between Firefly and the respective organizer or venue." },
  { type: "p", text: "Organizers or venues wishing to modify or remove an event or any published information about it can contact us at contact@fireflyapp.ro." },
  { type: "h2", text: "8. Prohibited Conduct" },
  { type: "p", text: "Users and partners are strictly prohibited from:" },
  { type: "ul", items: [
    "Using the platform for illegal purposes or to distribute harmful content.",
    "Attempting to compromise website security (hacking, automated scraping, unauthorized crawling, denial-of-service attacks).",
    "Impersonating another natural person or legal entity.",
    "Uploading materials that infringe upon the copyrights, registered trademarks, or image rights of third parties.",
  ] },
  { type: "h2", text: "9. Intellectual Property and Content" },
  { type: "p", text: "Your Content: You retain the copyright to the images, text, and logos you upload to the platform. By publishing them on fireflyapp.ro, you grant us a non-exclusive, royalty-free, worldwide license to display and promote such content within the application and on our official social media channels, for as long as the content is available on the platform and for a reasonable period thereafter, exclusively for the purpose of promoting Firefly and the published events." },
  { type: "callout", text: "Note: We reserve the right to remove, modify, or restrict access to any content that violates these Terms, applicable law, or the platform's rules." },
  { type: "p", text: "Platform Content: The design, source code, trademarks such as Firefly, and original text of the platform are the exclusive property of FIREFLY CONCEPT SRL." },
  { type: "h2", text: "10. Limitation of Liability (Disclaimer)" },
  { type: "p", text: "The platform is provided “as is.” To the fullest extent permitted by law, FIREFLY CONCEPT SRL shall not be liable for:" },
  { type: "ul", items: [
    "The cancellation, postponement, or modification of events or access conditions established by organizers.",
    "Incidents, damages, or material/physical harm suffered by users at venues or events promoted on the platform.",
    "Temporary interruptions of the service caused by technical errors, maintenance, or cyberattacks.",
  ] },
  { type: "callout", text: "Note: Event information is provided by organizers or venues. Firefly makes reasonable efforts to keep information up to date but does not guarantee that all information provided by third parties is complete, accurate, or up to date at all times." },
  { type: "h2", text: "11. Account Suspension" },
  { type: "p", text: "We reserve the right to temporarily or permanently suspend or terminate an account that violates these Terms, applicable law, or the platform's rules, including in cases of fraud, abuse, repeated violations, or threats to the security of the platform." },
  { type: "h2", text: "12. Applicable Law and Jurisdiction" },
  { type: "p", text: "These Terms are governed by Romanian law. In the case of users who benefit from the protection granted under consumer protection legislation, the applicable mandatory provisions, including those concerning jurisdiction, shall also apply. In all other cases, disputes shall be resolved by the competent courts in accordance with applicable law." },
  { type: "h2", text: "13. Platform Availability" },
  { type: "p", text: "Firefly makes reasonable efforts to keep the platform available and functional but does not guarantee uninterrupted operation or the absence of errors. The platform may be temporarily unavailable due to maintenance, updates, technical issues, or circumstances beyond Firefly's control." },
  { type: "h2", text: "14. Amendments to the Terms" },
  { type: "p", text: "We reserve the right to modify these Terms in accordance with changes in legislation or the functionality of the website. Amendments become effective upon publication on the website. Continued use of the website after the amendments take effect constitutes acceptance of the amended Terms." },
  ],
};

export const termsContent: Record<"en" | "ro", LegalDocument> = { en, ro };
